# problem #2
# Write a program that calculates the profit generated by a movie theatre for different ticket tickets.

# For VIP tickets, the profit is 30% of the ticket price + Rs120 for every ticket sold.
# For General tickets, the profit is 20% of the ticket price + Rs80 for every ticket sold.
# For Matinee show tickets, the profit is a flat 15% of the ticket price.
# Input: Ticket price and number of tickets sold for each ticket class.
# Output: Calculate and print the total revenue generated by the theatre in a day.

def calc_profit(price, tickets_sold, profit, add_charge):
    return (profit * price + add_charge) * tickets_sold


def main():
    ticket_info = {
        "VIP": {"profit": 0.25, "add_charge": 100},
        "General": {"profit": 0.15, "add_charge": 70},
        "Matinee_show": {"profit": 0.05, "add_charge": 0}
    }
    tickets = ["VIP", "General", "Matinee show"]
    total_profit = 0

    for ticket_range, info in ticket_info.items():
        price = float(input(f"Enter price for {ticket_range} class ticket: "))
        tickets_sold = int(
            input(f"Enter number of {ticket_range} class tickets sold: "))

        profit = calc_profit(price, tickets_sold,
                             info["profit"], info["add_charge"])
        total_profit += profit

    print("Total profit for the railways:", total_profit)


if __name__ == "__main__":
    main()
